# Generated by Django 3.1.7 on 2021-02-26 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategories',
            old_name='course',
            new_name='category',
        ),
    ]
